language: ruby
rvm: 2.3.0
env: CODECLIMATE_REPO_TOKEN=d69084d39be74e8dafe9a689102b19130a21abe963dce8aa6146078098c9b242
before_script:
  - rails db:create
  - cp config/application.yml.example config/application.yml
  - cp config/database.yml.example config/database.yml
script:
  - bundle exec rails db:reset
  - bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
