language: ruby
rvm: 2.3.0
env: CODECLIMATE_REPO_TOKEN=eab6c8947bd012a12d3742c121d2375d1450a08f3410d1ddcab4d7f9f686278d
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
script:
  - bundle exec rails db:reset
  - bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
