# UMass Transit Microservices Engine
# Router API Data Endpoint Configuration

# REQUIRED field
# The name of the microservice
name: 'ntdsurveys'

# REQUIRED field
# The URI for the site hosting the microservice
# NOTE: Do not attach the /v1/data to this.
uri: ''

# REQUIRED field
# Verification token
security_token: ''

# REQUIRED Field
# Endpoint of Microservices router
router_uri: ''

# OPTIONAL field (leave blank if not applicable)
# The models that the service can give info on
accessible_models: []
