# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 242083307c793e3067162981bbd1fea8654b0c6b57842279b230e857cf2590afbe4bfed7f785b54ac3bdff894f3f92e12d0cbb5d7938455ac6147391c75fe9e3

test:
  secret_key_base: 5add85a3ab9b59f88b275f1274f32ad99d51103db1c8af9ec1aac691922021722b2c8ba119d895e38e02307611ccb91e31df04e567c9eda8b580b19087c36083

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
